# การวิเคราะห์ข้อมูลสถิติผู้เล่น NBA

In [ ]:
import pandas as pd

df = pd.read_csv("/content/nba-player-data.csv")

## 1. การโหลดและตรวจสอบข้อมูล

In [ ]:
df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,PF-C,24,TOT,74,18,21.9,3.2,6.3,...,.616,2.6,4.0,6.6,1.3,0.6,0.9,1.1,1.9,7.6
1,1,Precious Achiuwa,C,24,TOR,25,0,17.5,3.1,6.8,...,.571,2.0,3.4,5.4,1.8,0.6,0.5,1.2,1.6,7.7
2,1,Precious Achiuwa,PF,24,NYK,49,18,24.2,3.2,6.1,...,.643,2.9,4.3,7.2,1.1,0.6,1.1,1.1,2.1,7.6
3,2,Bam Adebayo,C,26,MIA,71,71,34.0,7.5,14.3,...,.755,2.2,8.1,10.4,3.9,1.1,0.9,2.3,2.2,19.3
4,3,Ochai Agbaji,SG,23,TOT,78,28,21.0,2.3,5.6,...,.661,0.9,1.8,2.8,1.1,0.6,0.6,0.8,1.5,5.8

In [ ]:
df.tail()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
731,568,Thaddeus Young,PF,35,PHO,10,0,8.9,1.1,2.1,...,.333,1.7,1.1,2.8,0.7,0.5,0.2,0.4,1.1,2.3
732,569,Trae Young,PG,25,ATL,54,54,36.0,8.0,18.7,...,.855,0.4,2.3,2.8,10.8,1.3,0.2,4.4,2.0,25.7
733,570,Omer Yurtseven,C,25,UTA,48,12,11.4,2.1,3.8,...,.679,1.5,2.8,4.3,0.6,0.2,0.4,0.8,1.1,4.6
734,571,Cody Zeller,C,31,NOP,43,0,7.4,0.6,1.4,...,.605,1.1,1.5,2.6,0.9,0.2,0.1,0.4,1.0,1.8
735,572,Ivica Zubac,C,26,LAC,68,68,26.4,5.0,7.6,...,.723,2.9,6.3,9.2,1.4,0.3,1.2,1.2,2.6,11.7

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      736 non-null    object
 1   Player  736 non-null    object
 2   Pos     736 non-null    object
 3   Age     735 non-null    float64
 4   Tm      736 non-null    object
 5   G       736 non-null    object
 6   GS      736 non-null    object
 7   MP      736 non-null    object
 8   FG      736 non-null    object
 9   FGA     736 non-null    object
 10  FG%     728 non-null    object
 11  3P      736 non-null    object
 12  3PA     735 non-null    float64
 13  3P%     690 non-null    object
 14  2P      736 non-null    object
 15  2PA     736 non-null    object
 16  2P%     723 non-null    object
 17  eFG%    728 non-null    object
 18  FT      736 non-null    object
 19  FTA     736 non-null    object
 20  FT%     676 non-null    float64
 21  ORB     736 non-null    object
 22  DRB     736 non-null    object
 23  TRB     736 non-null    object
 24  AST     736 non-null    object
 25  STL     736 non-null    object
 26  BLK     736 non-null    object
 27  TOV     736 non-null    object
 28  PF      736 non-null    object
 29  PTS     735 non-null    float64
dtypes: float64(4), object(26)
memory usage: 172.6+ KB

In [ ]:
df.dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

## 2. การตรวจสอบข้อมูล

In [ ]:
df[df["Player"] == "Player"]

Empty DataFrame
Columns: [Rk, Player, Pos, Age, Tm, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, Age_Group, Ast_Group]
Index: []

[0 rows x 32 columns]

In [ ]:
df = df[df["Player"] != "Player"].copy()

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors = "coerce")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 735 entries, 0 to 735
Data columns (total 33 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Rk         735 non-null    object
 1   Player     735 non-null    object
 2   Pos        735 non-null    object
 3   Age        735 non-null    float64
 4   Tm         735 non-null    object
 5   G          735 non-null    object
 6   GS         735 non-null    object
 7   MP         735 non-null    float64
 8   FG         735 non-null    object
 9   FGA        735 non-null    object
 10  FG%        727 non-null    object
 11  3P         735 non-null    object
 12  3PA        735 non-null    float64
 13  3P%        689 non-null    float64
 14  2P         735 non-null    object
 15  2PA        735 non-null    object
 16  2P%        722 non-null    object
 17  eFG%       727 non-null    object
 18  FT         735 non-null    object
 19  FTA        735 non-null    object
 20  FT%        676 non-null    float64
 21  ORB        735 non-null    object
 22  DRB        735 non-null    object
 23  TRB        735 non-null    object
 24  AST        735 non-null    float64
 25  STL        735 non-null    object
 26  BLK        735 non-null    object
 27  TOV        735 non-null    float64
 28  PF         735 non-null    object
 29  PTS        735 non-null    float64
 30  Age_Group  735 non-null    object
 31  Ast_Group  735 non-null    object
 32  Mp_Group   735 non-null    object
dtypes: float64(8), object(25)
memory usage: 195.2+ KB

In [ ]:
df[["Player","Rk","Pos"]].head()

             Player Rk   Pos
0  Precious Achiuwa  1  PF-C
1  Precious Achiuwa  1     C
2  Precious Achiuwa  1    PF
3       Bam Adebayo  2     C
4      Ochai Agbaji  3    SG

## 3. การตรวจสอบ Missing value

In [ ]:
df[["Player","Rk","Pos"]].isna().sum()

Player    0
Rk        0
Pos       0
dtype: int64

In [ ]:
df["PTS"] = pd.to_numeric(df["PTS"],errors = "coerce")
df["FT%"] = pd.to_numeric(df["FT%"], errors = "coerce")
df["3PA"] = pd.to_numeric(df["3PA"], errors = "coerce")
df["3P%"] = pd.to_numeric(df["3P%"], errors ="coerce")

In [ ]:
df[df["3P%"].isna()]
#แสดงผู้เล่นที่มีค่างว่างใน column 3P%
#การคำนวน 3 เเต้ม 3P / 3PA

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,18,Udoka Azubuike,C,24,PHO,16,0,7.1,1.0,1.4,...,.231,0.7,1.3,2.0,0.2,0.1,0.4,0.3,1.1,2.2
24,19,Ibou Badji,C,21,POR,22,1,10.3,0.6,1.0,...,.500,0.9,1.4,2.3,0.6,0.1,0.9,0.7,2.1,1.5
53,36,Darius Bazley,PF,23,PHI,3,0,3.3,0.0,0.3,...,NaN,0.0,0.3,0.3,0.7,0.0,0.0,0.3,0.0,0.0
68,46,Bismack Biyombo,C,31,TOT,40,27,19.8,1.9,3.3,...,.481,1.6,3.7,5.2,1.3,0.3,0.9,1.1,2.2,4.4
69,46,Bismack Biyombo,C,31,MEM,30,27,23.9,2.2,4.0,...,.478,1.9,4.5,6.4,1.7,0.3,1.1,1.3,2.7,5.2
70,46,Bismack Biyombo,C,31,OKC,10,0,7.3,0.7,1.2,...,.500,0.5,1.3,1.8,0.2,0.1,0.3,0.4,0.7,1.8
80,53,Marques Bolden,C,25,MIL,2,0,1.5,0.0,0.0,...,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.5,0.0
106,74,Moses Brown,C,24,POR,22,5,9.1,1.5,3.0,...,.290,1.7,2.2,3.9,0.3,0.2,0.3,0.5,1.2,3.4
127,91,Colin Castleton,C,23,LAL,16,0,3.7,0.6,1.0,...,1.000,0.4,0.4,0.8,0.2,0.1,0.0,0.2,0.7,1.5
128,92,Malcolm Cazalon,SG,22,DET,1,0,3.0,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149,111,Jalen Crutcher,PG,24,NOP,1,0,3.0,0.0,1.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161,121,Moussa Diabaté,C,22,LAC,11,0,5.8,0.9,1.7,...,.643,1.4,0.8,2.2,0.4,0.5,0.1,0.2,0.4,2.6
163,122,Mamadi Diakite,PF,27,SAS,3,0,5.3,1.3,1.7,...,.667,0.3,0.7,1.0,0.7,0.0,0.3,0.0,0.3,4.0
165,123,Hamidou Diallo,SG,25,WAS,2,0,2.5,0.5,1.0,...,NaN,1.0,0.0,1.0,0.5,1.0,0.0,0.5,0.5,1.0
216,161,Daniel Gafford,C-PF,25,TOT,74,66,24.5,4.7,6.5,...,.674,2.6,5.0,7.6,1.6,0.9,2.1,1.0,3.1,11.0
217,161,Daniel Gafford,C,25,WAS,45,45,26.5,4.5,6.5,...,.706,2.9,5.1,8.0,1.5,1.0,2.2,1.0,3.3,10.9
218,161,Daniel Gafford,PF,25,DAL,29,21,21.5,5.0,6.4,...,.607,2.2,4.7,6.9,1.6,0.7,1.9,1.0,2.8,11.2
271,201,Ron Harper Jr.,PF,23,TOR,1,0,4.0,0.0,0.0,...,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0
274,204,Kevon Harris,SG,26,ORL,2,0,3.0,1.0,1.5,...,NaN,0.0,1.0,1.0,0.5,0.0,0.0,0.5,1.5,2.0
276,206,Shaquille Harrison,SG,30,MEM,3,0,2.0,0.3,0.7,...,NaN,0.0,0.7,0.7,0.0,0.0,0.3,0.0,0.0,0.7
299,224,Richaun Holmes,C,30,DAL,23,2,10.3,1.4,2.6,...,.571,1.4,2.0,3.4,0.7,0.1,0.4,0.5,1.4,3.4
322,246,Justin Jackson,SF,28,MIN,2,0,0.5,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
323,247,Quenton Jackson,PG,25,IND,3,0,3.7,0.0,0.3,...,1.000,0.0,1.3,1.3,0.7,0.3,0.0,0.0,0.3,0.7
330,254,Trey Jemison,C,24,TOT,25,14,22.9,3.0,5.4,...,.840,2.6,2.8,5.4,1.1,0.5,1.1,1.4,2.8,6.8
331,254,Trey Jemison,C,24,WAS,2,0,0.5,0.0,0.0,...,NaN,0.0,0.5,0.5,0.0,0.0,0.0,0.5,0.0,0.0
332,254,Trey Jemison,C,24,MEM,23,14,24.9,3.3,5.9,...,.840,2.8,3.0,5.8,1.2,0.5,1.2,1.4,3.0,7.4
349,271,DeAndre Jordan,C,35,DEN,36,2,11.0,1.6,2.6,...,.491,1.5,2.9,4.4,0.7,0.2,0.4,0.6,1.6,3.9
375,295,Kira Lewis Jr.,PG,22,TOR,1,0,2.0,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
399,311,Théo Maledon,PG,22,PHO,4,0,3.3,0.3,1.0,...,1.000,0.0,0.3,0.3,0.0,0.0,0.0,0.8,0.8,1.3
432,336,Nathan Mensah,C,25,CHO,25,0,12.3,0.5,1.1,...,.750,1.2,1.4,2.6,0.4,0.2,0.6,0.6,2.6,1.3
491,377,Markquis Nowell,SG,24,TOR,1,0,4.0,0.0,1.0,...,1.000,2.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0
517,395,Filip Petrušev,C,23,TOT,3,0,3.3,0.3,0.7,...,.500,0.0,0.3,0.3,0.0,0.0,0.0,0.0,0.3,1.0
518,395,Filip Petrušev,C,23,PHI,1,0,3.0,0.0,0.0,...,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
519,395,Filip Petrušev,C,23,SAC,2,0,3.5,0.5,1.0,...,.500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,1.5
525,401,Jakob Poeltl,C,28,TOR,50,50,26.4,5.0,7.6,...,.551,2.9,5.7,8.6,2.5,0.7,1.5,1.5,3.0,11.1
545,419,Neemias Queta,C,24,BOS,28,0,11.9,2.4,3.7,...,.714,1.9,2.5,4.4,0.7,0.5,0.8,0.5,1.8,5.5
562,434,Mitchell Robinson,C,25,NYK,31,21,24.8,2.4,4.1,...,.409,4.6,3.9,8.5,0.6,1.2,1.1,0.8,1.8,5.6
581,447,Adama Sanogo,PF,21,CHI,9,0,7.3,1.6,3.0,...,.667,2.1,1.9,4.0,0.0,0.1,0.0,0.6,0.6,4.0
601,463,Ben Simmons,PG,27,BRK,15,12,23.9,2.9,4.9,...,.400,2.1,5.9,7.9,5.7,0.8,0.6,1.8,2.4,6.1
605,467,Jericho Sims,C,25,NYK,45,11,13.0,0.8,1.2,...,.667,1.2,2.0,3.3,0.6,0.2,0.4,0.4,1.0,2.0
606,468,Dmytro Skapintsev,C,25,NYK,2,0,1.0,0.0,0.5,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,470,Javonte Smart,PG,24,PHI,1,0,1.0,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
654,508,Oscar Tshiebwe,PF,24,IND,8,0,5.3,1.3,2.5,...,.750,1.0,1.0,2.0,0.3,0.3,0.1,0.0,0.4,3.3
711,555,Mark Williams,C,22,CHO,19,19,26.7,5.2,7.9,...,.719,4.0,5.7,9.7,1.2,0.8,1.1,0.9,2.6,12.7
713,557,Robert Williams,C,26,POR,6,0,19.8,2.8,4.3,...,.778,1.8,4.5,6.3,0.8,1.2,1.2,1.2,2.8,6.8
735,572,Ivica Zubac,C,26,LAC,68,68,26.4,5.0,7.6,...,.723,2.9,6.3,9.2,1.4,0.3,1.2,1.2,2.6,11.7

In [ ]:
df[df["3P%"].isna()][["Player","3P","3PA","3P%"]]
# missing value ของคอลัมน์ 3P% ไม่ได้เกิดจากข้อมูลสูญหาย เเต่เกิดจากไม่สามารถคำนวนค่าได้ (3P/3PA = 3P%)

                 Player   3P  3PA  3P%
23       Udoka Azubuike  0.0  0.0  NaN
24           Ibou Badji  0.0  0.0  NaN
53        Darius Bazley  0.0  0.0  NaN
68      Bismack Biyombo  0.0  0.0  NaN
69      Bismack Biyombo  0.0  0.0  NaN
70      Bismack Biyombo  0.0  0.0  NaN
80       Marques Bolden  0.0  0.0  NaN
106         Moses Brown  0.0  0.0  NaN
127     Colin Castleton  0.0  0.0  NaN
128     Malcolm Cazalon  0.0  0.0  NaN
149      Jalen Crutcher  0.0  0.0  NaN
161      Moussa Diabaté  0.0  0.0  NaN
163      Mamadi Diakite  0.0  0.0  NaN
165      Hamidou Diallo  0.0  0.0  NaN
216      Daniel Gafford  0.0  0.0  NaN
217      Daniel Gafford  0.0  0.0  NaN
218      Daniel Gafford  0.0  0.0  NaN
271      Ron Harper Jr.  0.0  0.0  NaN
274        Kevon Harris  0.0  0.0  NaN
276  Shaquille Harrison  0.0  0.0  NaN
299      Richaun Holmes  0.0  0.0  NaN
322      Justin Jackson  0.0  0.0  NaN
323     Quenton Jackson  0.0  0.0  NaN
330        Trey Jemison  0.0  0.0  NaN
331        Trey Jemison  0.0  0.0  NaN
332        Trey Jemison  0.0  0.0  NaN
349      DeAndre Jordan  0.0  0.0  NaN
375      Kira Lewis Jr.  0.0  0.0  NaN
399        Théo Maledon  0.0  0.0  NaN
432       Nathan Mensah  0.0  0.0  NaN
491     Markquis Nowell  0.0  0.0  NaN
517      Filip Petrušev  0.0  0.0  NaN
518      Filip Petrušev  0.0  0.0  NaN
519      Filip Petrušev  0.0  0.0  NaN
525        Jakob Poeltl  0.0  0.0  NaN
545       Neemias Queta  0.0  0.0  NaN
562   Mitchell Robinson  0.0  0.0  NaN
581        Adama Sanogo  0.0  0.0  NaN
601         Ben Simmons  0.0  0.0  NaN
605        Jericho Sims  0.0  0.0  NaN
606   Dmytro Skapintsev  0.0  0.0  NaN
608       Javonte Smart  0.0  0.0  NaN
654      Oscar Tshiebwe  0.0  0.0  NaN
711       Mark Williams  0.0  0.0  NaN
713     Robert Williams  0.0  0.0  NaN
735         Ivica Zubac  0.0  0.0  NaN

In [ ]:
df[df["FG%"].isna()]
# FG/FGA = FG%
df[df["FG%"].isna()][["Player","FG","FGA","FG%"]]
# ผู้เล่นไม่ได้ทำเเต้มทำให้ไม่มีค่า FG%(จำนวนลูกที่ยิงลง)

              Player   FG  FGA  FG%
80    Marques Bolden  0.0  0.0  NaN
128  Malcolm Cazalon  0.0  0.0  NaN
271   Ron Harper Jr.  0.0  0.0  NaN
322   Justin Jackson  0.0  0.0  NaN
331     Trey Jemison  0.0  0.0  NaN
375   Kira Lewis Jr.  0.0  0.0  NaN
518   Filip Petrušev  0.0  0.0  NaN
608    Javonte Smart  0.0  0.0  NaN

In [ ]:
df[df["2P%"].isna()][["Player","2P","2PA","2P%"]]
# missing value เกิดจากไม่สามารถคำนวนค่าได้

               Player   2P  2PA  2P%
20   Ryan Arcidiacono  0.0  0.0  NaN
80     Marques Bolden  0.0  0.0  NaN
128   Malcolm Cazalon  0.0  0.0  NaN
164    Mamadi Diakite  0.0  0.0  NaN
241     Jacob Gilyard  0.0  0.0  NaN
271    Ron Harper Jr.  0.0  0.0  NaN
322    Justin Jackson  0.0  0.0  NaN
331      Trey Jemison  0.0  0.0  NaN
375    Kira Lewis Jr.  0.0  0.0  NaN
518    Filip Petrušev  0.0  0.0  NaN
608     Javonte Smart  0.0  0.0  NaN
656       P.J. Tucker  0.0  0.0  NaN
720     Dylan Windler  0.0  0.0  NaN

In [ ]:
df[df["eFG%"].isna()][["Player","FG","FGA","3P","eFG%"]]
# eFG = (FG+0.5(3P))/FGA missing value เกิดจากไม่สามารถคำนวนค่าได้

              Player   FG  FGA   3P eFG%
80    Marques Bolden  0.0  0.0  0.0  NaN
128  Malcolm Cazalon  0.0  0.0  0.0  NaN
271   Ron Harper Jr.  0.0  0.0  0.0  NaN
322   Justin Jackson  0.0  0.0  0.0  NaN
331     Trey Jemison  0.0  0.0  0.0  NaN
375   Kira Lewis Jr.  0.0  0.0  0.0  NaN
518   Filip Petrušev  0.0  0.0  0.0  NaN
608    Javonte Smart  0.0  0.0  0.0  NaN

In [ ]:
df[df["FT%"].isna()][[ "Player","FT","FTA","FT%"]]
# FT% = FT/FTA missing value เกิดจากการไม่สามารถคำนวนค่าได้

                    Player   FT  FTA  FT%
20        Ryan Arcidiacono  0.0  0.0  NaN
28                  Player   FT  FTA  NaN
50           Nicolas Batum  0.0  0.0  NaN
53           Darius Bazley  0.0  0.0  NaN
80          Marques Bolden  0.0  0.0  NaN
86          Jamaree Bouyea  0.0  0.0  NaN
87          Jamaree Bouyea  0.0  0.0  NaN
88          Jamaree Bouyea  0.0  0.0  NaN
94      Izaiah Brockington  0.0  0.0  NaN
101      Charlie Brown Jr.  0.0  0.0  NaN
128        Malcolm Cazalon  0.0  0.0  NaN
149         Jalen Crutcher  0.0  0.0  NaN
164         Mamadi Diakite  0.0  0.0  NaN
165         Hamidou Diallo  0.0  0.0  NaN
190        Tosan Evbuomwan  0.0  0.0  NaN
195           Adam Flagler  0.0  0.0  NaN
212             Alex Fudge  0.0  0.0  NaN
214            Andrew Funk  0.0  0.0  NaN
226           Kaiser Gates  0.0  0.0  NaN
231             Taj Gibson  0.0  0.0  NaN
235            Harry Giles  0.0  0.0  NaN
241          Jacob Gilyard  0.0  0.0  NaN
250           RaiQuan Gray  0.0  0.0  NaN
252            Danny Green  0.0  0.0  NaN
271         Ron Harper Jr.  0.0  0.0  NaN
274           Kevon Harris  0.0  0.0  NaN
276     Shaquille Harrison  0.0  0.0  NaN
322         Justin Jackson  0.0  0.0  NaN
331           Trey Jemison  0.0  0.0  NaN
333              Ty Jerome  0.0  0.0  NaN
340       Keyontae Johnson  0.0  0.0  NaN
375         Kira Lewis Jr.  0.0  0.0  NaN
386     Kenneth Lofton Jr.  0.0  0.0  NaN
419            Skylar Mays  0.0  0.0  NaN
446            Patty Mills  0.0  0.0  NaN
462      Wendell Moore Jr.  0.0  0.0  NaN
516          Drew Peterson  0.0  0.0  NaN
518         Filip Petrušev  0.0  0.0  NaN
539          Jason Preston  0.0  0.0  NaN
540           Joshua Primo  0.0  0.0  NaN
570           Ryan Rollins  0.0  0.0  NaN
602           Kobi Simmons  0.0  0.0  NaN
606      Dmytro Skapintsev  0.0  0.0  NaN
607          Jalen Slawson  0.0  0.0  NaN
608          Javonte Smart  0.0  0.0  NaN
618            Pat Spencer  0.0  0.0  NaN
636           Daniel Theis  0.0  0.0  NaN
639          Isaiah Thomas  0.0  0.0  NaN
651  Juan Toscano-Anderson  0.0  0.0  NaN
656            P.J. Tucker  0.0  0.0  NaN
659           Hunter Tyson  0.0  0.0  NaN
674          Ish Wainright  0.0  0.0  NaN
684    TyTy Washington Jr.  0.0  0.0  NaN
696             Jack White  0.0  0.0  NaN
717            D.J. Wilson  0.0  0.0  NaN
719          Dylan Windler  0.0  0.0  NaN
720          Dylan Windler  0.0  0.0  NaN
721          Dylan Windler  0.0  0.0  NaN
722          Dylan Windler  0.0  0.0  NaN
724            Isaiah Wong  0.0  0.0  NaN

## 4. การวิเคราะห์ข้อมูล

In [ ]:
df_3p = df[df["3PA"]>0]

In [ ]:
df_3p["3P%"].isna().sum()

np.int64(0)

In [ ]:
df_3p.shape

(675, 33)

In [ ]:
df_3p[["Player","3P","3PA","3P%"]].head()

             Player   3P  3PA   3P%
0  Precious Achiuwa  0.4  1.3  .268
1  Precious Achiuwa  0.5  1.9  .277
2  Precious Achiuwa  0.3  1.0  .260
3       Bam Adebayo  0.2  0.6  .357
4      Ochai Agbaji  0.8  2.7  .294

### 4.1 ผู้เล่น 10 อันดับแรกที่มีค่า PTS สูงสุด

In [ ]:

top_10 = df.sort_values("PTS" , ascending = False)
top_10[["Player","Tm","Pos","PTS"]].head(10)

                      Player   Tm Pos   PTS
187              Joel Embiid  PHI   C  34.7
172              Luka Dončić  DAL  PG  33.9
14     Giannis Antetokounmpo  MIL  PF  30.4
236  Shai Gilgeous-Alexander  OKC  PG  30.1
110            Jalen Brunson  NYK  PG  28.7
181             Kevin Durant  PHO  PF  27.1
82              Devin Booker  PHO  PG  27.1
631             Jayson Tatum  BOS  PF  26.9
455         Donovan Mitchell  CLE  SG  26.6
208             De'Aaron Fox  SAC  PG  26.6

In [ ]:
df["PTS"].describe()

count    735.000000
mean       8.022313
std        6.481825
min        0.000000
25%        3.400000
50%        6.100000
75%       11.050000
max       34.700000
Name: PTS, dtype: float64

### 4.2 ค่า PTS เฉลี่ยตามตำแหน่ง

In [ ]:
df.groupby("Pos")["PTS"].mean()

Pos
C         7.729412
C-PF      7.100000
PF        8.265306
PF-C      7.600000
PF-SF     5.700000
PG        8.640816
PG-SG    12.925000
SF        7.225161
SF-PF     9.800000
SF-SG    12.100000
SG        8.118182
SG-PG     3.300000
Name: PTS, dtype: float64

In [ ]:
df.groupby("Pos").size()
#เป็นการบอกว่าเเต่ละกลุ่มมีกี่จำนวนเเถว

Pos
C        119
C-PF       3
PF       147
PF-C       1
PF-SF      1
PG       147
PG-SG      4
SF       155
SF-PF      2
SF-SG      1
SG       154
SG-PG      1
dtype: int64

In [ ]:
main_pos = ["C","PF","PG","SF","SG"]
df_main = df[df["Pos"].isin(main_pos)]
df_main.groupby("Pos")["PTS"].mean()
#เราไม่เอาตำเเหน่งที่มีข้อมูลน้อยมาเปรียบเทียบ

Pos
C     7.729412
PF    8.265306
PG    8.640816
SF    7.225161
SG    8.118182
Name: PTS, dtype: float64

### 4.3 ค่า PTS เฉลี่ยตามช่วงอายุ

In [ ]:
import numpy as np
df["Age_Group"] = np.where(
    df["Age"]<25,
    "Less than 25",
    "25 and older"
)

In [ ]:
df[["Age","Age_Group"]].head(10)

    Age     Age_Group
0  24.0  Less than 25
1  24.0  Less than 25
2  24.0  Less than 25
3  26.0  25 and older
4  23.0  Less than 25
5  23.0  Less than 25
6  23.0  Less than 25
7  23.0  Less than 25
8  25.0  25 and older
9  28.0  25 and older

In [ ]:
df.groupby("Age_Group")["PTS"].mean()

Age_Group
25 and older    8.643571
Less than 25    7.193968
Name: PTS, dtype: float64

In [ ]:
df["MP"] = pd.to_numeric(df["MP"],errors="coerce")

### 4.4 ค่า PTS เฉลี่ยตามเวลาที่ลงเล่น

In [ ]:
import numpy as np
df["Mp_Group"] = np.where(
    df["MP"]<10,
    "Less than 10",
    "10 and more"
)
df[["MP","Mp_Group"]].head(10)

     MP     Mp_Group
0  21.9  10 and more
1  17.5  10 and more
2  24.2  10 and more
3  34.0  10 and more
4  21.0  10 and more
5  19.7  10 and more
6  23.6  10 and more
7  26.5  10 and more
8  23.4  10 and more
9  33.5  10 and more

In [ ]:
df.groupby("Mp_Group")["PTS"].mean()

Mp_Group
10 and more     9.793838
Less than 10    1.997006
Name: PTS, dtype: float64

In [ ]:
df["AST"] = pd.to_numeric(df["AST"] , errors = "coerce")
df["TOV"] = pd.to_numeric(df["TOV"], errors = "coerce")

### 4.5 ความสัมพันธ์ระหว่าง Assist และ Turnover

In [ ]:
import numpy as np
df["Ast_Group"] = np.where(
    df["AST"]<2,
    "Less than 2",
    "2 and more"
)

In [ ]:
df[["AST","Ast_Group","TOV"]].head(10)

   AST    Ast_Group  TOV
0  1.3  Less than 2  1.1
1  1.8  Less than 2  1.2
2  1.1  Less than 2  1.1
3  3.9   2 and more  2.3
4  1.1  Less than 2  0.8
5  0.9  Less than 2  0.7
6  1.3  Less than 2  1.1
7  2.3   2 and more  1.1
8  2.5   2 and more  0.9
9  3.0   2 and more  1.3

In [ ]:
df.groupby("Ast_Group")["TOV"].mean()

Ast_Group
2 and more     1.639608
Less than 2    0.574375
Name: TOV, dtype: float64

In [ ]:

df[["AST","TOV"]].isna().sum()

AST    0
TOV    0
dtype: int64

### ความสัมพันธ์ระหว่าง Assist (AST) และ Turnover (TOV)

คำนวณค่าสหสัมพันธ์ระหว่าง Assist และ Turnover
เพื่อดูว่าตัวแปรทั้งสองมีความสัมพันธ์กันในทิศทางใด

In [ ]:
df["AST"].corr(df["TOV"])

np.float64(0.8313129477608738)

## 5. Insights ที่ได้จากการวิเคราะห์


ตำแหน่งที่มี PTS เฉลี่ยสูงสุด
จากข้อมูลพบว่าตำเเหน่งที่มีค่าเฉลี่ย PTS สูงสุดคือ PG ซึ่งมีค่าเฉลี่ยอยู่ที่ 8.64 คะเเนนต่อเกม ขณะที่ SG มีค่า PTS เฉลี่ยประมาณ 8.12 คะเเนนต่อเกม ซึ่งเเสดงให้เห็นว่า ในข้อมูลชุดนี้มีเเนวโน้มว่าตำเเหน่ง PG จะมีค่า PTS เฉลี่ยสูงกว่าผู้เล่นตำเเหน่ง SG

ผู้เล่นกลุ่มอายุไหนที่มีคะเเนนเฉลี่ยสูงกว่า
จากข้อมูลพบว่าผู้เล่นที่มีอายุ 25 ปีขึ้นไป มีค่า PTS เฉลี่ยต่อเกมอยู่ที่ประมาณ 8.64 คะเเนนต่อเกม ซึ่งมากกว่าคะเเนน PTS เฉลี่ยของผู้เล่นที่มีอายุน้อยกว่า 25 ปีอยู่ที่ประมาณ 7.19 คะแนนต่อเกม

พบความสัมพันธ์ระหว่างอะไรบ้าง
จากข้อมูล ค่าสหสัมพันธ์ระหว่าง Assist(AST) เเละ Turnover(TOV) อยู่ที่ 0.8313 ซึ่งเเสดงให้เห็นว่าตัวเเปรทั้งสองมีความสัมพันธ์เชิงบวกค่อนข้างสูง โดยในชุดข้อมูลนี้ ผู้เล่นที่มีค่า Assist สูงมีเเนวโน้มที่จะมีค่า Turnover สูงตามไปด้วย